version: "3.8"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=expressPrisma
      - POSTGRES_PASSWORD=expressPrisma
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432
volumes:
  postgres:
